### ISSUE TITLE
Just a hello

### ISSUE THREAD

**Issue by yob1997** [jonaro00/AutoTrader#1]
Hi man! Super cool that you created this, I was thinking of scripting something similar. But didn't want to get into the the phone Python to phone work around. Awesome that you came up with a solution! I'll look deeper into your code the coming month(s) might have some ideas or optimizations. And would love to help you develop this thing! It's really cool. Pokemon should get a batch trade options for Best Friends someday, but it will probably never happen. 
Maybe a batch evolve script would also be really helpful! 

Quick question how did you manage to take into account the time it take to complete the trade and the load in time for both phones? Since that load in time sometimes varies between trades (did not investigate the code yet so maybe I'm asking the obvious here). 
Any ways I'm rambling, kudos for making something like this!

**Comment by jonaro00** [comment]
Hi!

I agree that Batch Trading should be added, this is a "temporary" fix.

When googling for similar projects to this one, you'll find ones that use more advanced tools such as screenshots and image-to-text to automate it further. The disadvantage of those are the increased setup and usage time, but also the increased development, debugging, and troubleshooting time. There are many ideas for more features and optimizations, but didn't want to invest lots of development time for some small time saves, while also risking to sacrifice ease of use. And this tool *could* be made totally obsolete if Batch Trading was to be added.
Therefore, this project aims for a more simple, robust and easy to use tool.

I've also had the idea to make an auto evolve script :). The challenge there is that the button is positioned differently for different Pokémon due to Lucky/Shadow/Mega Energy, and that this introduces the need to scroll to the evolve button. This would require screenshots/screen reading to accomplish. A fun project to attempt perhaps ;).

> how did you manage to take into account the time it take to complete the trade and the load in time for both phones?

The delays between clicks are hard-coded and chosen with enough margin to account for most cases of lag occurring. This is of course the main place where time optimizing could be done, but it is left simple due to the points mentioned above.

Now I'm the one rambling.
Thanks for showing interest! Feel free to come with suggestions :)

**Comment by yob1997** [comment]
Hey man!

I've not yet had the time to look into it. But I've found a phone app that does clicks 'autoclickerapp' me and my girlfriend have been using it successfully to do the trading automatically! No need to hook it in the pc aswell that way.

Just wanted to let you know that is is also an option, but it's probably a bit more buggy.

Best regards!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
